language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
  
    
script: ./mvnw clean install

cache:
  directories:
    - $HOME/.m2

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY 
    bucket: oaz-web-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: cherrylime/SpringBootSample
      branch: master    