language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
    
script: ./mvnw clean install

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - mkdir -p deploy
  - cp /home/travis/build/cherrylime/SpringBootSample/target/*.jar ./deploy  


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY 
    bucket: oaz-web-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: cherrylime/SpringBootSample
      branch: master    
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: oaz-web-deploy
    key: SpringSample-0.0.1-SNAPSHOT.jar
    application: oszSample
    deployment_group: oaz-web-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: cherrylime/SpringBootSample
      branch: master      
      