version: 0.0
os: linux
files:
  - source:  /
    destination: /home/cherrylime/applications/SpringSample
    overwrite: yes
    
hooks:
  AfterInstall: 
    - location: execute-deploy.sh
      timeout: 180    
      runas: root